#!/usr/bin/env bash
confDir="${XDG_CONFIG_HOME:-$HOME/.config}"
thmDcol="$confDir/wallbash/theme.wallbash"
subTarget="$confDir/gtk-4.0/gtk.css"
subTarget1="$confDir/gtk-3.0/gtk.css"

if [[ -f ${subTarget} || -f ${subTarget1} ]]; then
  :
else
  echo "
  /* --Auto Generated by Wallbash-- // */
  /* // --------------------------------- */

  @define-color accent_color       #<wallbash_pry2>
  @define-color accent_fg_color    #<wallbash_txt1>;
  @define-color accent_bg_color    #<wallbash_pry2>;
  @define-color window_bg_color    #<wallbash_pry1>;
  @define-color window_fg_color    #<wallbash_txt1>;
  @define-color headerbar_bg_color #<wallbash_pry1>;
  @define-color headerbar_fg_color #<wallbash_txt1>;
  @define-color popover_bg_color   #<wallbash_pry1>;
  @define-color popover_fg_color   #<wallbash_txt1>;
  @define-color view_bg_color      #<wallbash_pry1>;
  @define-color view_fg_color      #<wallbash_txt1>;
  @define-color card_bg_color      #<wallbash_pry1>;
  @define-color card_fg_color      #<wallbash_txt1>;
  @define-color sidebar_bg_color   #<wallbash_pry1>;
  @define-color sidebar_fg_color   #<wallbash_txt1>;
  @define-color sidebar_border_color #<wallbash_pry1>;
  @define-color sidebar_backdrop_color #<wallbash_pry1>;

  /* // --------------------------------- */
  /* --Auto Generated by Wallbash-- // */
  " >> "$subTarget"
  cp "$subTarget" "$subTarget1"
fi

declare -A wallbash

while IFS='=' read -r key val; do
  [[ -z "$key" || -z "$val" ]] && continue
  wallbash["$key"]="$val"
done < "$thmDcol"

sed -i \
  -E "s|(@define-color)([[:space:]]+accent_color)([[:space:]]+).*|\1\2\3${wallbash[wallbash_pry2]};|g" \
  "$subTarget"

sed -i \
  -E "s|(@define-color)([[:space:]]+accent_fg_color)([[:space:]]+).*|\1\2\3${wallbash[wallbash_txt1]};|g" \
  "$subTarget"

sed -i \
  -E "s|(@define-color)([[:space:]]+accent_bg_color)([[:space:]]+).*|\1\2\3${wallbash[wallbash_pry2]};|g" \
  "$subTarget"

sed -i \
  -E "s|(@define-color)([[:space:]]+window_bg_color)([[:space:]]+).*|\1\2\3${wallbash[wallbash_pry1]};|g" \
  "$subTarget"

sed -i \
  -E "s|(@define-color)([[:space:]]+window_fg_color)([[:space:]]+).*|\1\2\3${wallbash[wallbash_txt1]};|g" \
  "$subTarget"

sed -i \
  -E "s|(@define-color)([[:space:]]+headerbar_bg_color)([[:space:]]+).*|\1\2\3${wallbash[wallbash_pry1]};|g" \
  "$subTarget"

sed -i \
  -E "s|(@define-color)([[:space:]]+headerbar_fg_color)([[:space:]]+).*|\1\2\3${wallbash[wallbash_txt1]};|g" \
  "$subTarget"

sed -i \
  -E "s|(@define-color)([[:space:]]+popover_bg_color)([[:space:]]+).*|\1\2\3${wallbash[wallbash_pry1]};|g" \
  "$subTarget"

sed -i \
  -E "s|(@define-color)([[:space:]]+popover_fg_color)([[:space:]]+).*|\1\2\3${wallbash[wallbash_txt1]};|g" \
  "$subTarget"

sed -i \
  -E "s|(@define-color)([[:space:]]+view_bg_color)([[:space:]]+).*|\1\2\3${wallbash[wallbash_pry1]};|g" \
  "$subTarget"

sed -i \
  -E "s|(@define-color)([[:space:]]+view_fg_color)([[:space:]]+).*|\1\2\3${wallbash[wallbash_txt1]};|g" \
  "$subTarget"

sed -i \
  -E "s|(@define-color)([[:space:]]+card_bg_color)([[:space:]]+).*|\1\2\3${wallbash[wallbash_pry1]};|g" \
  "$subTarget"

sed -i \
  -E "s|(@define-color)([[:space:]]+card_fg_color)([[:space:]]+).*|\1\2\3${wallbash[wallbash_txt1]};|g" \
  "$subTarget"

sed -i \
  -E "s|(@define-color)([[:space:]]+sidebar_bg_color)([[:space:]]+).*|\1\2\3${wallbash[wallbash_pry1]};|g" \
  "$subTarget"

sed -i \
  -E "s|(@define-color)([[:space:]]+sidebar_fg_color)([[:space:]]+).*|\1\2\3${wallbash[wallbash_txt1]};|g" \
  "$subTarget"


sed -i \
  -E "s|(@define-color)([[:space:]]+sidebar_backdrop_color)([[:space:]]+).*|\1\2\3${wallbash[wallbash_pry1]};|g" \
  "$subTarget"


sed -i \
  -E "s|(@define-color)([[:space:]]+sidebar_border_color)([[:space:]]+).*|\1\2\3${wallbash[wallbash_pry1]};|g" \
  "$subTarget"

cp "$subTarget" "$subTarget1"
{
    pkill -SIGUSR2 nautilus || true &
    pkill -SIGUSR2 file-roller || true &
    pkill -SIGUSR2 gnome-system-monitor || true &
    pkill -SIGUSR2 gnome-disks || true &
    pkill -SIGUSR2 nwg-look || true &
    DISPLAY= nautilus --quit || true &
} > /dev/null 2>&1

echo "[Wallbash-GTK] GTK Color Generation Reloaded"
exit

